# Generated by Django 3.2.7 on 2022-05-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_state_country'),
        ('customer', '0003_auto_20220504_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermanentResident',
            new_name='BecomePermanentResident',
        ),
    ]
