# Generated by Django 3.2.7 on 2022-05-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_state_country'),
        ('customer', '0004_rename_permanentresident_becomepermanentresident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='accomidation_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'NO')], default='no', max_length=20, verbose_name='Are you requesting an accommodation because of a disability and/or impairment?'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='explanation',
            field=models.ManyToManyField(blank=True, null=True, to='master.ApplicableBoxes', verbose_name='Please check any applicable boxes and provide an explanation'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_daytime_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Daytime Phone Number'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail(if any)'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile phone Number(if any)'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_postal_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Intepreter_state', to='master.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_streat_number_and_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street Number and Name'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='intepreter_zipcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='interpreter_business_or_organization_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Interpreter's Business or Organization Name"),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='interpreter_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Interpreter's First Name(Given Name)"),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='interpreter_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Which language was used?'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='interpreter_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Interpreter's Last Name(Family Name)"),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='other_social_security_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Social Security Number(if any) '),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_appartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prefererappartment', to='master.appartmenttype', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_appartment_value',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_business_or_organization_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Preparer's Business or Organization Name"),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prefere_country', to='master.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_daytime_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Daytime Phone Number'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail(if any)'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Preparer's First Name(Given Name)"),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Preparer's Last Name(Family Name)"),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile phone Number(if any)'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_postal_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferer_state', to='master.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreparerInformation', to='master.preparerinformation', verbose_name='Who prepared this application?'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_streat_number_and_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street Number and Name'),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='preparer_zipcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='alien_registration_number_status',
            field=models.BooleanField(default=False, verbose_name="I no longer have my card and can't find this information "),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='category_status',
            field=models.BooleanField(default=False, verbose_name="I no longer have my card and can't find this information"),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='resident_since_status',
            field=models.BooleanField(default=False, verbose_name="I no longer have my card and can't find this information"),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='adjustment_apply_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cusromer_Adj_Apply', to='master.uscisadjustmentstatus', verbose_name='Which USCIS office did you apply for adjustment of status? '),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='adjustment_granted_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cusromer_Adj_Granted', to='master.uscisadjustmentstatus', verbose_name='Which USCIS office granted your adjustment of Status? '),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='adjustment_status_interview',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'NO'), ("I Don't Know", "I Don't Know")], default='no', max_length=20, null=True, verbose_name='Did you have an adjustment of status interview?'),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='apply_enter_city_and_state_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter City and State'),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='consula_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cusromer_PermanentResident', to='master.state', verbose_name='Where was your destination when you came to the U.S.? '),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='consular_applied_visa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location where you applied for an immigrant visa '),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='consular_issued_visa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location where your immigrant visa was issued '),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='consular_port_of_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cusromer_Pot', to='master.portofentry', verbose_name='Port of Entry'),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='granted_enter_city_and_state_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter City and State '),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='other_uscis_office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Which USCIS office did you apply for adjustment of status?'),
        ),
        migrations.AlterField(
            model_name='becomepermanentresident',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.permanentresident', verbose_name='How did you get your permanent resident or conditional permanent resident status?'),
        ),
        migrations.RemoveField(
            model_name='biographicinformation',
            name='race',
        ),
        migrations.AddField(
            model_name='biographicinformation',
            name='race',
            field=models.ManyToManyField(blank=True, null=True, to='master.Race'),
        ),
    ]
