# Generated by Django 3.2.7 on 2022-05-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220505_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='alien_registration_number_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="I no longer have my card and can't find this information "),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='category_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="I no longer have my card and can't find this information"),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='resident_since_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="I no longer have my card and can't find this information"),
        ),
    ]
