# Generated by Django 3.2.7 on 2022-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_state_country'),
        ('customer', '0008_alter_applicantinformation_preparer_appartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='explanation',
            field=models.ManyToManyField(to='master.ApplicableBoxes', verbose_name='Please check any applicable boxes and provide an explanation'),
        ),
    ]
