# Generated by Django 3.2.7 on 2022-05-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrationsection',
            name='title',
            field=models.TextField(),
        ),
    ]
